#!/bin/sh
#MSUB -A asccasc
#MSUB -l partition=cab
#MSUB -l nodes=8
#MSUB -l walltime=03:30:00
#MSUB -q pbatch
#MSUB -o /g/g90/mitra3/work/IRS/build.space/codes_debug/test_old_dump_216.txt
#MSUB -e /g/g90/mitra3/work/IRS/build.space/codes_debug/test_old_dump_216.txt



export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs0";export PIN_FAULTY_FUNC=FunctionTimer_init;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs1";export PIN_FAULTY_FUNC=icdot;export PIN_FAULTY_EXEC=31;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs2";export PIN_FAULTY_FUNC=initbuf;export PIN_FAULTY_EXEC=41;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs3";export PIN_FAULTY_FUNC=rmatmult3;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs4";export PIN_FAULTY_FUNC=MPI_Isend_Wrapper;export PIN_FAULTY_EXEC=33;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs5";export PIN_FAULTY_FUNC=MPI_Waitall_Wrapper;export PIN_FAULTY_EXEC=31;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs6";export PIN_FAULTY_FUNC=ProblemArray_add;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs7";export PIN_FAULTY_FUNC=FunctionTimer_clock;export PIN_FAULTY_EXEC=22;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs8";export PIN_FAULTY_FUNC=MPI_Allreduce_Wrapper;export PIN_FAULTY_EXEC=28;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs9";export PIN_FAULTY_FUNC=ProblemArray_ptr;export PIN_FAULTY_EXEC=48;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs10";export PIN_FAULTY_FUNC=hash_del2;export PIN_FAULTY_EXEC=48;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs11";export PIN_FAULTY_FUNC=ProblemArray_del;export PIN_FAULTY_EXEC=44;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs12";export PIN_FAULTY_FUNC=FunctionTimer_initialize;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs13";export PIN_FAULTY_FUNC=comreduce;export PIN_FAULTY_EXEC=40;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs14";export PIN_FAULTY_FUNC=hash_lookup_elm;export PIN_FAULTY_EXEC=28;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs15";export PIN_FAULTY_FUNC=FunctionTimer_lookup;export PIN_FAULTY_EXEC=21;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs16";export PIN_FAULTY_FUNC=setpz2;export PIN_FAULTY_EXEC=39;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs17";export PIN_FAULTY_FUNC=hash_lookup_obj;export PIN_FAULTY_EXEC=25;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs18";export PIN_FAULTY_FUNC=FunctionTimer_construct;export PIN_FAULTY_EXEC=45;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs19";export PIN_FAULTY_FUNC=getdata;export PIN_FAULTY_EXEC=31;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs20";export PIN_FAULTY_FUNC=FunctionTimer_initialize;export PIN_FAULTY_EXEC=21;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs21";export PIN_FAULTY_FUNC=hash_add;export PIN_FAULTY_EXEC=45;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs22";export PIN_FAULTY_FUNC=waitbuf;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs23";export PIN_FAULTY_FUNC=MPI_Isend_Wrapper;export PIN_FAULTY_EXEC=8;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs24";export PIN_FAULTY_FUNC=strsave;export PIN_FAULTY_EXEC=14;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs25";export PIN_FAULTY_FUNC=FunctionTimer_lookup;export PIN_FAULTY_EXEC=23;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs26";export PIN_FAULTY_FUNC=setpz2;export PIN_FAULTY_EXEC=47;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs27";export PIN_FAULTY_FUNC=rbndcom;export PIN_FAULTY_EXEC=50;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs28";export PIN_FAULTY_FUNC=rgst_get_dims_of_type;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs29";export PIN_FAULTY_FUNC=rmatmult3;export PIN_FAULTY_EXEC=39;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs30";export PIN_FAULTY_FUNC=FunctionTimer_finalize;export PIN_FAULTY_EXEC=37;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs31";export PIN_FAULTY_FUNC=FunctionTimer_init;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs32";export PIN_FAULTY_FUNC=MPI_Waitall_Wrapper;export PIN_FAULTY_EXEC=40;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs33";export PIN_FAULTY_FUNC=MPI_Allreduce_Wrapper;export PIN_FAULTY_EXEC=44;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs34";export PIN_FAULTY_FUNC=icdot;export PIN_FAULTY_EXEC=39;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs35";export PIN_FAULTY_FUNC=hash_lookup_obj;export PIN_FAULTY_EXEC=42;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs36";export PIN_FAULTY_FUNC=putdata;export PIN_FAULTY_EXEC=28;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs37";export PIN_FAULTY_FUNC=getdata;export PIN_FAULTY_EXEC=48;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs38";export PIN_FAULTY_FUNC=rgst_list_attr;export PIN_FAULTY_EXEC=39;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs39";export PIN_FAULTY_FUNC=FunctionTimer_construct;export PIN_FAULTY_EXEC=19;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs40";export PIN_FAULTY_FUNC=ProblemArray_ptr;export PIN_FAULTY_EXEC=49;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs41";export PIN_FAULTY_FUNC=MPI_Wait_Wrapper;export PIN_FAULTY_EXEC=11;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs42";export PIN_FAULTY_FUNC=FunctionTimer_construct;export PIN_FAULTY_EXEC=3;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs43";export PIN_FAULTY_FUNC=rgst_get_dims_of_type;export PIN_FAULTY_EXEC=48;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs44";export PIN_FAULTY_FUNC=MPI_Allreduce_Wrapper;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs45";export PIN_FAULTY_FUNC=initbuf;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs46";export PIN_FAULTY_FUNC=putdata;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs47";export PIN_FAULTY_FUNC=FunctionTimer_finalize;export PIN_FAULTY_EXEC=9;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs48";export PIN_FAULTY_FUNC=ProblemArray_add;export PIN_FAULTY_EXEC=43;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_216.irs49";export PIN_FAULTY_FUNC=waitbuf;export PIN_FAULTY_EXEC=34;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1106;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 216 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=216 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_216.old;date;
