#!/bin/sh
#MSUB -A asccasc
#MSUB -l partition=cab
#MSUB -l nodes=16
#MSUB -l walltime=03:30:00
#MSUB -q pbatch
#MSUB -o /g/g90/mitra3/work/IRS/build.space/codes_debug/test_old_dump_512.txt
#MSUB -e /g/g90/mitra3/work/IRS/build.space/codes_debug/test_old_dump_512.txt


export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs0";export PIN_FAULTY_FUNC=MPI_Wait_Wrapper;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs1";export PIN_FAULTY_FUNC=MPI_Waitany_Wrapper;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs2";export PIN_FAULTY_FUNC=FunctionTimer_clock;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs3";export PIN_FAULTY_FUNC=ProblemArray_ptr;export PIN_FAULTY_EXEC=10;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs4";export PIN_FAULTY_FUNC=getdata;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs5";export PIN_FAULTY_FUNC=FunctionTimer_lookup;export PIN_FAULTY_EXEC=2;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs6";export PIN_FAULTY_FUNC=hash_lookup_obj;export PIN_FAULTY_EXEC=10;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs7";export PIN_FAULTY_FUNC=MPI_Isend_Wrapper;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs8";export PIN_FAULTY_FUNC=freebuf;export PIN_FAULTY_EXEC=5;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs9";export PIN_FAULTY_FUNC=MPI_Wtime_Wrapper;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs10";export PIN_FAULTY_FUNC=MPI_Waitall_Wrapper;export PIN_FAULTY_EXEC=18;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs11";export PIN_FAULTY_FUNC=putdata;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs12";export PIN_FAULTY_FUNC=MPI_Allreduce_Wrapper;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs13";export PIN_FAULTY_FUNC=MPI_Irecv_Wrapper;export PIN_FAULTY_EXEC=5;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs14";export PIN_FAULTY_FUNC=waitbuf;export PIN_FAULTY_EXEC=15;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs15";export PIN_FAULTY_FUNC=FunctionTimer_initialize;export PIN_FAULTY_EXEC=3;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs16";export PIN_FAULTY_FUNC=rbndcom;export PIN_FAULTY_EXEC=2;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs17";export PIN_FAULTY_FUNC=rmatmult3;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs18";export PIN_FAULTY_FUNC=rmatmult;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs19";export PIN_FAULTY_FUNC=initbuf;export PIN_FAULTY_EXEC=2;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs20";export PIN_FAULTY_FUNC=FunctionTimer_init;export PIN_FAULTY_EXEC=11;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs21";export PIN_FAULTY_FUNC=TimeStepControl_find;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs22";export PIN_FAULTY_FUNC=FunctionTimer_construct;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs23";export PIN_FAULTY_FUNC=FunctionTimer_finalize;export PIN_FAULTY_EXEC=9;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs24";export PIN_FAULTY_FUNC=strsave;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs25";export PIN_FAULTY_FUNC=hash_add;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs26";export PIN_FAULTY_FUNC=setpz2;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs27";export PIN_FAULTY_FUNC=setpz1;export PIN_FAULTY_EXEC=13;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs28";export PIN_FAULTY_FUNC=icdot;export PIN_FAULTY_EXEC=13;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs29";export PIN_FAULTY_FUNC=postbuf;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs30";export PIN_FAULTY_FUNC=icdot;export PIN_FAULTY_EXEC=3;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs31";export PIN_FAULTY_FUNC=freebuf;export PIN_FAULTY_EXEC=15;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs32";export PIN_FAULTY_FUNC=FunctionTimer_initialize;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs33";export PIN_FAULTY_FUNC=MPI_Irecv_Wrapper;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs34";export PIN_FAULTY_FUNC=rgst_get_t;export PIN_FAULTY_EXEC=5;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs35";export PIN_FAULTY_FUNC=MPI_Wait_Wrapper;export PIN_FAULTY_EXEC=15;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs36";export PIN_FAULTY_FUNC=FunctionTimer_lookup;export PIN_FAULTY_EXEC=6;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs37";export PIN_FAULTY_FUNC=MPI_Waitany_Wrapper;export PIN_FAULTY_EXEC=9;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs38";export PIN_FAULTY_FUNC=TimeStepControl_find;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs39";export PIN_FAULTY_FUNC=setpz1;export PIN_FAULTY_EXEC=8;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs40";export PIN_FAULTY_FUNC=MPI_Isend_Wrapper;export PIN_FAULTY_EXEC=19;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs41";export PIN_FAULTY_FUNC=FunctionTimer_clock;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs42";export PIN_FAULTY_FUNC=initbuf;export PIN_FAULTY_EXEC=5;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs43";export PIN_FAULTY_FUNC=rbndcom;export PIN_FAULTY_EXEC=3;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs44";export PIN_FAULTY_FUNC=strsave;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs45";export PIN_FAULTY_FUNC=FunctionTimer_construct;export PIN_FAULTY_EXEC=13;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs46";export PIN_FAULTY_FUNC=comreduce;export PIN_FAULTY_EXEC=2;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs47";export PIN_FAULTY_FUNC=MPI_Wtime_Wrapper;export PIN_FAULTY_EXEC=6;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs48";export PIN_FAULTY_FUNC=putdata;export PIN_FAULTY_EXEC=20;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs49";export PIN_FAULTY_FUNC=FunctionTimer_init;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs50";export PIN_FAULTY_FUNC=hash_lookup_obj;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs51";export PIN_FAULTY_FUNC=ProblemArray_ptr;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs52";export PIN_FAULTY_FUNC=rmatmult;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs53";export PIN_FAULTY_FUNC=MPI_Allreduce_Wrapper;export PIN_FAULTY_EXEC=6;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs54";export PIN_FAULTY_FUNC=MPI_Waitall_Wrapper;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs55";export PIN_FAULTY_FUNC=getdata;export PIN_FAULTY_EXEC=6;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs56";export PIN_FAULTY_FUNC=hash_lookup_elm;export PIN_FAULTY_EXEC=2;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs57";export PIN_FAULTY_FUNC=hash_add;export PIN_FAULTY_EXEC=13;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs58";export PIN_FAULTY_FUNC=waitbuf;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_512.irs59";export PIN_FAULTY_FUNC=rmatmult3;export PIN_FAULTY_EXEC=9;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=irs1107;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_old/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 16 -n 512 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/IRS/build.space/codes_debug/irs zrad3d -child_io_off -k 008MPI -def NDOMS=512 >> /g/g90/mitra3/work/IRS/build.space/codes_debug/injector_old_512.old;date;
