#!/bin/sh
#MSUB -A asccasc
#MSUB -l partition=cab
#MSUB -l nodes=8
#MSUB -l walltime=03:30:00
#MSUB -q pbatch
#MSUB -o /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/test_dump_256.txt
#MSUB -e /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/test_dump_256.txt


export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps0";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic14unpack_reverseEiPiPd;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps1";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic15unpack_exchangeEPd;export PIN_FAULTY_EXEC=10;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps2";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic13pack_exchangeEiPd;export PIN_FAULTY_EXEC=27;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps3";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Memory8sreallocEPviPc;export PIN_FAULTY_EXEC=6;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps4";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS5Timer5stampEv;export PIN_FAULTY_EXEC=47;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps5";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS8Neighbor9coord2binEPd;export PIN_FAULTY_EXEC=14;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps6";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6FixNVE15final_integrateEv;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps7";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic11create_atomEiPd;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps8";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS4Comm11communicateEv;export PIN_FAULTY_EXEC=34;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps9";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic9pack_commEiPiPdiS1_;export PIN_FAULTY_EXEC=30;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps10";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Modify15final_integrateEv;export PIN_FAULTY_EXEC=25;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps11";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic14unpack_reverseEiPiPd;export PIN_FAULTY_EXEC=30;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps12";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Verlet11force_clearEi;export PIN_FAULTY_EXEC=3;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps13";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic15unpack_exchangeEPd;export PIN_FAULTY_EXEC=37;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps14";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Memory7smallocEiPc;export PIN_FAULTY_EXEC=46;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps15";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Memory8sreallocEPviPc;export PIN_FAULTY_EXEC=25;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps16";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6FixNVE15final_integrateEv;export PIN_FAULTY_EXEC=35;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps17";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS4Comm11communicateEv;export PIN_FAULTY_EXEC=49;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps18";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic4copyEii;export PIN_FAULTY_EXEC=30;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps19";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS4Comm19reverse_communicateEv;export PIN_FAULTY_EXEC=17;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps20";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic9pack_commEiPiPdiS1_;export PIN_FAULTY_EXEC=32;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps21";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS8Neighbor9coord2binEPd;export PIN_FAULTY_EXEC=5;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps22";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS7Lattice11lattice2boxERdS1_S1_;export PIN_FAULTY_EXEC=14;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps23";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic13pack_exchangeEiPd;export PIN_FAULTY_EXEC=5;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps24";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS7RanPark7uniformEv;export PIN_FAULTY_EXEC=11;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps25";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic11create_atomEiPd;export PIN_FAULTY_EXEC=14;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps26";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS5Timer5stampEv;export PIN_FAULTY_EXEC=35;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps27";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS8Neighbor6decideEv;export PIN_FAULTY_EXEC=7;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps28";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS7RanPark5resetEiPd;export PIN_FAULTY_EXEC=4;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps29";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS9PairLJCut7computeEii;export PIN_FAULTY_EXEC=46;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps30";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS7RanPark7uniformEv;export PIN_FAULTY_EXEC=30;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps31";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Modify15final_integrateEv;export PIN_FAULTY_EXEC=13;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps32";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic4copyEii;export PIN_FAULTY_EXEC=19;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps33";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS8Neighbor9coord2binEPd;export PIN_FAULTY_EXEC=15;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps34";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Memory7smallocEiPc;export PIN_FAULTY_EXEC=39;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps35";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic14unpack_reverseEiPiPd;export PIN_FAULTY_EXEC=38;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps36";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS7Lattice11lattice2boxERdS1_S1_;export PIN_FAULTY_EXEC=14;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps37";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic9pack_commEiPiPdiS1_;export PIN_FAULTY_EXEC=29;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps38";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic11create_atomEiPd;export PIN_FAULTY_EXEC=35;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps39";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Memory8sreallocEPviPc;export PIN_FAULTY_EXEC=47;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps40";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6Memory8sreallocEPviPc;export PIN_FAULTY_EXEC=32;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps41";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6FixNVE17initial_integrateEv;export PIN_FAULTY_EXEC=19;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps42";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS8Neighbor9coord2binEPd;export PIN_FAULTY_EXEC=16;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps43";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS7RanPark7uniformEv;export PIN_FAULTY_EXEC=12;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps44";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic13pack_exchangeEiPd;export PIN_FAULTY_EXEC=3;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps45";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS7RanPark5resetEiPd;export PIN_FAULTY_EXEC=11;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps46";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic9pack_commEiPiPdiS1_;export PIN_FAULTY_EXEC=8;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps47";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS4Comm11communicateEv;export PIN_FAULTY_EXEC=47;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps48";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS6FixNVE15final_integrateEv;export PIN_FAULTY_EXEC=34;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
export PIN_INJECT=1;export PIN_LOCK_FILE="/g/g90/mitra3/lock_256.lammps49";export PIN_FAULTY_FUNC=_ZN9LAMMPS_NS13AtomVecAtomic15unpack_exchangeEPd;export PIN_FAULTY_EXEC=28;export PIN_ENTRY_FUNC=myEntry;export PIN_EXIT_FUNC=myExit;export PIN_PROFILE_IMG=lmp_g++;export AUT_USE_CALL_PATH=TRUE;export AUT_TIMEOUT=60;export LD_LIBRARY_PATH=/usr/local/tools/mvapich2-gnu-1.7/lib:/g/g90/mitra3/work/for_cab/automaded_LA_24Oct/install/lib:/usr/local/tools/fftw/lib:/usr/global/tools/adept/callpath/chaos_5_x86_64_ib/lib:/usr/global/tools/adept-utils/chaos_5_x86_64_ib/lib;

srun -O -N 8 -n 256 pin -t /g/g90/mitra3/work/pin-2.12-58423-gcc.4.4.7-linux/source/tools/profile_MPI_frequency/obj-intel64/profile_MPI_frequency.so -- /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/lmp_g++ -var x 40 -var y 40 -var z 80 < in.lj >> /g/g90/mitra3/work/LAMMPS/lammps-22Jun07/bench/injector_output_256.txt;date;
