export LOOPITERSKIP_PFUP='1'
export LOOPCHANGE_PFUPDATE='1'

export LOOPITERSKIP_IEINSIDE_OUTER='1'
export LOOPCHANGE_IEINSIDE_OUTER='1'
export LOOPITERSKIP_IEINSIDE_INNER='1'
export LOOPCHANGE_IEINSIDE_INNER='1'

export LOOPITERSKIP_IEEDGE_OUTER='1'
export LOOPCHANGE_IEEDGE_OUTER='1'
export LOOPITERSKIP_IEEDGE_INNER='1'
export LOOPCHANGE_IEEDGE_INNER='1'


export LOOPITERSKIP_PFUPDATE='1'
export LOOPCHANGE_PFUPDATE='1'

export LOOPITERSKIP_IEINSIDE_OUTER='1'
export LOOPCHANGE_IEINSIDE_OUTER='1'

export LOOPITERSKIP_IEINSIDE_INNER='1'
export LOOPCHANGE_IEINSIDE_INNER='1'

export LOOPITERSKIP_IEEDGE_OUTER='1'
export LOOPCHANGE_IEEDGE_OUTER='1'

export LOOPITERSKIP_IEEDGE_INNER='1'
export LOOPCHANGE_IEEDGE_INNER='1'

export LOOPCHANGE_INSIDEERROR_OUTER='1'
export LOOPITERSKIP_INSIDEERROR_OUTER='1'

export LOOPCHANGE_INSIDEERROR_INNER='1'
export LOOPITERSKIP_INSIDEERROR_INNER='1'

export LOOPCHANGE_EDGEERROR_1='1'
export LOOPITERSKIP_EDGEERROR_1='1'

export LOOPCHANGE_EDGEERROR_2='1'
export LOOPITERSKIP_EDGEERROR_2='1'
export PHASETOAPPROXIMATE='1'
export PARTICLE_FACTOR_CHANGE='1'
export TOTALPHASES='1'
export TOTALITERATIONS='1'

